### ISSUE TITLE
404 for package lookup for mvdan.cc/lint

### ISSUE THREAD

**Issue by fin09pcap** [mvdan/mvdan.cc#3]
Rel: https://github.com/mvdan/mvdan.cc/issues/2 https://github.com/mvdan/mvdan.cc/issues/1

The following package is reporting a `404` similar to the above issues.

```
mvdan.cc/lint@v0.0.0-20170908181259-adc824a0674b: unrecognized import path "mvdan.cc/lint": reading https://mvdan.cc/lint?go-get=1: 404 Not Found
```

**Comment by mvdan** [comment]
What software uses it still? It has been completely dead and archived for years. I thought I could get away with making it a 404 for good.

**Comment by mvdan** [comment]
Ah, of course, my own software still uses it, like unindent.
