### ISSUE TITLE
Company proxy blocking mvdan.cc

### ISSUE THREAD

**Issue by harg** [mvdan/mvdan.cc#4]
Hello,
I want to install gopls. It requires mvdan.cc/xurls and mvdan.cc/gofumpt modules.
Sadly, my company network is blocking mvdan.cc domain.
How can i install those modules and then install gopls?

Thank you in advance.

**Comment by mvdan** [comment]
I'm not sure what to tell you. Ask your company? There's nothing wrong with my site :)

But also, you no longer need to even talk to mvdan.cc if you use a module proxy: https://proxy.golang.org/

Closing for now since there's nothing I can do here.
